_screen.Visible= .F.
***SISTEM INFORMASI OPERASIONAL UNIT KENDARAAN
***DIBUAT OLEH RUKI KURNIAWAN
SET TALK OFF
SET DATE ITALIAN
SET CENTURY ON
SET DEFAULT TO D:\BARUAPK
DO FORM FUTAMA.SCX
READ EVENTS
RETURN
